---
title: "Untitled"
author: "Carolina Villarreal"
date: "5/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# find correlation of 2020 with other years

find the performance of each index with past years and find a correlation by year. 




```{r}
require("quantmod")
```

```{r}


sp500 <- getSymbols("^GSPC", from="1928-01-01",to = "2020-12-31", auto.assign = FALSE)


# splitting the data by years

byYr = split(sp500, f="years")
```

```{r}
# calculate returns for the year

byYrRet <- lapply(byYr, function(x) ROC(x, type="discrete"))

# strip index, just leave year for reference

byYrRet <- lapply(byYrRet, function(x){
  x[is.na(x)] <- 0 
  yr= as.data.frame(format(index(x), format="%Y"))
  colnames(yr) = "Year"
  dat = as.data.frame(coredata(x))
  colnames(dat) = "data"
  cbind(yr,dat)
})
```

```{r}

#plot all years against current year

plot(cumsum(byYrRet[[2]]$data), type="l", ylim=c(-.8,.8))
for(ii in 3:length(byYrRet))
{
  lines(cumsum(byYrRet[[ii]]$data))
}
lines(cumsum(byYrRet[[length(byYrRet)]]$data), col="green")
```

```{r}
# find correlation

THIS = cumsum(byYrRet[[length(byYrRet)]]$data)

corr = lapply(as.list(2:length(byYrRet)), function(x){
  YR = as.data.frame(unique(byYrRet[[x]]$Year))
  VS = byYrRet[[x]]$data
  VS = cumsum(VS[1:length(THIS)])
  VS = as.data.frame(round(cor(VS, THIS), 4))
  VS = cbind(YR, VS)
  colnames(VS) = c("Year", "Correlation")
    VS
})

corr = do.call(rbind, corr)
```

```{r}
YRS0 = c(2009, 1958,1955)
YRS = (YRS0 - 1928)+1

i = YRS[1]
cols = c("blue", "black", "grey", "green")
plot(cumsum(byYrRet[[i]]$data), type="l", ylim=c(-.4,.4),
     ylab="Return", xlab="Days", col=cols[1])
for(ii in 2:length(YRS))
{
  loc = YRS[ii]
  lines(cumsum(byYrRet[[loc]]$data), col=cols[ii])
}
lines(THIS, col=cols[length(cols)])
legend("bottomright",
       legend=c(YRS0,2020),
       bty = "n",
       col = cols,
       pch = 2,
       pt.cex = 1,
       cex = 0.45,
       horiz = TRUE,
       text.col = "black")
```

there is a strong correlation between the year 2020 and 2009, 1958 and 1955.

###########################################################

# get constituents of S&P 500
```{r}
read.csv("/Users/carolinavillarreal/Desktop/TESIS/tesis/SPY ETF.csv", header = TRUE)
```

```{r}

```

```{r}

```

##############################################
momentum
########################################


```{r}
require("PerformanceAnalytics"); require("quantmod"); require("pbapply"); require("data.table")
```

```{r}

e <- new.env()
tickers <- c("AMZN", "BIDU", "GLD", "GOOGL", "GS", "IWM", "NFLX", "MMM", "DIA", "SPY")
getSymbols(tickers, from="2003-01-01", env=e)
PRC <- do.call(merge,eapply(e,Ad))
```
```{r}
if(last(index(PRC)) != Sys.Date())
{
  last <- pblapply(as.list(gsub(".Adjusted", "", names(PRC))), getQuote)
  PRC <- rbind(PRC,xts(coredata(t(rbindlist(last)$Last)), order.by=Sys.Date()))
}
```

```{r}
NOM <- colnames(PRC) <- gsub(".Adjusted", "", names(PRC))

MOMO60 <- round(ROC(PRC,n=60,type="discrete"),4)

MOMO60 <- MOMO60["20030331::"]
PRC <- PRC["20030331::"]

indx <- seq(as.Date("2003-03-31"), length.out = 300, by = "4 weeks")
SELECT <- MOMO60[paste(indx)]; dim(SELECT)
```

```{r}
indx2 <- ifelse((indx %in% index(SELECT) == FALSE), paste(indx+1), paste(indx))

SELECT <- MOMO60[paste(indx2)];dim(SELECT)
PRC2 <- PRC[paste(indx2)];dim(SELECT)

ASSETS4 <- combn(NOM, 4)
```

```{r}
MOMO = function(x)
{
  y <- ASSETS4[,x]
  S <- SELECT[,y]
  
  SEQ <- as.numeric(apply(S,1,which.max))
  prc2 <- round(PRC2[,y],2)
  RETS <- CalculateReturns(prc2, "discrete")
  
  ALL <- do.call(merge, lapply(as.list(1:ncol(RETS)), function(x){
    Lag(reclass(ifelse(SEQ==x,1,0), match.to = S)*RETS[,x])
  }))
  
  colnames(ALL) <- names(prc2)
  ALL[is.na(ALL)] <- 0
  
  EQT <- reclass(rowSums(ALL), match.to = ALL);EQT[is.na(EQT)] <- 0
  colnames(EQT) <- paste(names(prc2), collapse = "-")
  EQT
}

STRAT <- pblapply(as.list(1:ncol(ASSETS4)), function(x) MOMO(x))
```

```{r}
AAA <- pblapply(STRAT,colSums)

df <- STRAT[order(sapply(AAA, "[[",1))]
df <- df[(length(df)-9):length(df)]
TOP10 <- do.call(merge,df)

charts.PerformanceSummary(TOP10, cex.legend=0.45, colorset=rich10equal, geometric = TRUE, main = "TOP10")
table.Stats(TOP10)
chart.RiskReturnScatter(TOP10, add.sharpe = c(1), Rf=(0.03/sqrt(252)),
                        colorset = rich10equal, xlim = c(0.45,0.55), ylim = c(1.4,1.75))
```

```{r}
AAA <- lapply(df,colSums)
AAA[[which.max(AAA)]]
EQT <- df[[which.max(AAA)]]

charts.PerformanceSummary(EQT, geometric = TRUE)
table.Stats(EQT)
table.Drawdowns(EQT)
```

